# Site
name: "Quốc Định"
description: "Blog của quốc định"
meta_description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'

google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  quocdinhit:
    name: Quốc Định
    display_name: Quốc Định
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: pqd1997@gmail.com
    web: https://www.quocdinhit.tk
    facebook:  https://facebook.com/PhungQuocDinh
    description: "MÁY TÍNH là cổ máy ngu ngốc, có thể làm được những điều thông minh - DEV là những người thông minh, có thể làm những việc vô cùng ngu ngốc."
  quocdinh:
    name: Quốc Định
    display_name: Quốc Định
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: pqd1997@gmail.com
    web: https://www.quocdinhit.tk
    facebook: https://facebook.com/PhungQuocDinh
    description: "MÁY TÍNH là cổ máy ngu ngốc, có thể làm được những điều thông minh - DEV là những người thông minh, có thể làm những việc vô cùng ngu ngốc."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge